version: '3.8'

services:
  web:
    build: .
    container_name: cafeteria_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
